name: global
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_contacts: ^1.1.9+2
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/static_asset/

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/regular.ttf
    - family: semibold
      fonts:
        - asset: assets/fonts/semibold.ttf
